//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://ws.bancogalicia.com.ar/webservices/globales/bgbaresultadooperacion/2_0_0", ClrNamespace = "ws.bancogalicia.com.ar.webservices.globales.bgbaresultadooperacion._2_0_0")]

namespace BGBA.Models.N.Afip
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://ws.bancogalicia.com.ar/webservices/accionesautenticacionafip/1_0_0", ConfigurationName = "AccionesAutenticacionAFIP")]
    public interface AccionesAutenticacionAFIP
    {

        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de contenedor (http://ws.bancogalicia.com.ar/webservices/accionesautenticacionafip/autenticaryautorizarconsumowebservicerequest/1_0_0) del mensaje AutenticarYAutorizarConsumoWebserviceRequest no coincide con el valor predeterminado (http://ws.bancogalicia.com.ar/webservices/accionesautenticacionafip/1_0_0)
        [System.ServiceModel.OperationContractAttribute(Action = "http://ws.bancogalicia.com.ar/webservices/accionesautenticacionafip/autenticaryau" +
            "torizarconsumowebservice", ReplyAction = "*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ws.bancogalicia.com.ar.webservices.globales.bgbaresultadooperacion._2_0_0.BGBAResultadoOperacionFalla), Action = "http://ws.bancogalicia.com.ar/webservices/accionesautenticacionafip/autenticaryau" +
            "torizarconsumowebservice", Name = "BGBAResultadoOperacionFalla", Namespace = "http://ws.bancogalicia.com.ar/webservices/globales/bgbaresultadooperacion/2_0_0")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        AutenticarYAutorizarConsumoWebserviceResponse1 AutenticarYAutorizarConsumoWebservice(AutenticarYAutorizarConsumoWebserviceRequest1 request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://ws.bancogalicia.com.ar/webservices/accionesautenticacionafip/autenticaryau" +
            "torizarconsumowebservice", ReplyAction = "*")]
        System.Threading.Tasks.Task<AutenticarYAutorizarConsumoWebserviceResponse1> AutenticarYAutorizarConsumoWebserviceAsync(AutenticarYAutorizarConsumoWebserviceRequest1 request);
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ws.bancogalicia.com.ar/webservices/accionesautenticacionafip/autenticaryau" +
        "torizarconsumowebservicerequest/1_0_0")]
    public partial class AutenticarYAutorizarConsumoWebserviceRequest
    {

        private BGBAHeader bGBAHeaderField;

        private AutenticarYAutorizarConsumoWebserviceRequestDatos datosField;

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://ws.bancogalicia.com.ar/webservices/globales/bgbaheader/2_0_0", Order = 0)]
        public BGBAHeader BGBAHeader
        {
            get
            {
                return this.bGBAHeaderField;
            }
            set
            {
                this.bGBAHeaderField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public AutenticarYAutorizarConsumoWebserviceRequestDatos Datos
        {
            get
            {
                return this.datosField;
            }
            set
            {
                this.datosField = value;
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ws.bancogalicia.com.ar/webservices/globales/bgbaheader/2_0_0")]
    public partial class BGBAHeader
    {

        private Identificadores identificadoresField;

        private ModuloAplicativo moduloAplicativoField;

        private equipo equipoField;

        private Origen origenField;

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public Identificadores Identificadores
        {
            get
            {
                return this.identificadoresField;
            }
            set
            {
                this.identificadoresField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public ModuloAplicativo ModuloAplicativo
        {
            get
            {
                return this.moduloAplicativoField;
            }
            set
            {
                this.moduloAplicativoField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public equipo Equipo
        {
            get
            {
                return this.equipoField;
            }
            set
            {
                this.equipoField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public Origen Origen
        {
            get
            {
                return this.origenField;
            }
            set
            {
                this.origenField = value;
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ws.bancogalicia.com.ar/webservices/globales/bgbaheader/2_0_0")]
    public partial class Identificadores
    {

        private idMensaje idMensajeField;

        private idMensaje idMensajeAnteriorField;

        private idMensaje idOperacionField;

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public idMensaje IdMensaje
        {
            get
            {
                return this.idMensajeField;
            }
            set
            {
                this.idMensajeField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public idMensaje IdMensajeAnterior
        {
            get
            {
                return this.idMensajeAnteriorField;
            }
            set
            {
                this.idMensajeAnteriorField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public idMensaje IdOperacion
        {
            get
            {
                return this.idOperacionField;
            }
            set
            {
                this.idOperacionField = value;
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ws.bancogalicia.com.ar/webservices/globales/bgbaheader/2_0_0")]
    public partial class idMensaje
    {

        private string idEsquemaField;

        private string valueField;

        public idMensaje()
        {
            this.idEsquemaField = "UUI";
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("UUI")]
        public string idEsquema
        {
            get
            {
                return this.idEsquemaField;
            }
            set
            {
                this.idEsquemaField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ws.bancogalicia.com.ar/webservices/globales/bgbaheader/2_0_0")]
    public partial class organizacionInterna
    {

        private string tipoField;

        private ulong idField;

        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string tipo
        {
            get
            {
                return this.tipoField;
            }
            set
            {
                this.tipoField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ulong id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ws.bancogalicia.com.ar/webservices/globales/bgbaheader/2_0_0")]
    public partial class Origen
    {

        private ModuloAplicativo moduloAplicativoField;

        private string canalField;

        private organizacionInterna organizacionInternaField;

        private equipo equipoField;

        private string terminalField;

        private System.DateTime fechaHoraCreacionField;

        private bool fechaHoraCreacionFieldSpecified;

        private IdCliente idClienteField;

        private Operador operadorField;

        private string supervisionField;

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public ModuloAplicativo ModuloAplicativo
        {
            get
            {
                return this.moduloAplicativoField;
            }
            set
            {
                this.moduloAplicativoField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string Canal
        {
            get
            {
                return this.canalField;
            }
            set
            {
                this.canalField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public organizacionInterna OrganizacionInterna
        {
            get
            {
                return this.organizacionInternaField;
            }
            set
            {
                this.organizacionInternaField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public equipo Equipo
        {
            get
            {
                return this.equipoField;
            }
            set
            {
                this.equipoField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string Terminal
        {
            get
            {
                return this.terminalField;
            }
            set
            {
                this.terminalField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public System.DateTime FechaHoraCreacion
        {
            get
            {
                return this.fechaHoraCreacionField;
            }
            set
            {
                this.fechaHoraCreacionField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FechaHoraCreacionSpecified
        {
            get
            {
                return this.fechaHoraCreacionFieldSpecified;
            }
            set
            {
                this.fechaHoraCreacionFieldSpecified = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public IdCliente IdCliente
        {
            get
            {
                return this.idClienteField;
            }
            set
            {
                this.idClienteField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        public Operador Operador
        {
            get
            {
                return this.operadorField;
            }
            set
            {
                this.operadorField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 8)]
        public string Supervision
        {
            get
            {
                return this.supervisionField;
            }
            set
            {
                this.supervisionField = value;
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ws.bancogalicia.com.ar/webservices/globales/bgbaheader/2_0_0")]
    public partial class ModuloAplicativo
    {

        private string idGaliciaField;

        private string idConsumidorField;

        private string idProveedorField;

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string IdGalicia
        {
            get
            {
                return this.idGaliciaField;
            }
            set
            {
                this.idGaliciaField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string IdConsumidor
        {
            get
            {
                return this.idConsumidorField;
            }
            set
            {
                this.idConsumidorField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string IdProveedor
        {
            get
            {
                return this.idProveedorField;
            }
            set
            {
                this.idProveedorField = value;
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ws.bancogalicia.com.ar/webservices/globales/bgbaheader/2_0_0")]
    public partial class equipo
    {

        private string ipField;

        private string nombreField;

        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ip
        {
            get
            {
                return this.ipField;
            }
            set
            {
                this.ipField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ws.bancogalicia.com.ar/webservices/globales/bgbaheader/2_0_0")]
    public partial class IdCliente
    {

        private string idEsquemaField;

        private string valueField;

        public IdCliente()
        {
            this.idEsquemaField = "NV";
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("NV")]
        public string idEsquema
        {
            get
            {
                return this.idEsquemaField;
            }
            set
            {
                this.idEsquemaField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ws.bancogalicia.com.ar/webservices/globales/bgbaheader/2_0_0")]
    public partial class Operador
    {

        private string idEsquemaField;

        private string valueField;

        public Operador()
        {
            this.idEsquemaField = "LEGAJO";
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("LEGAJO")]
        public string idEsquema
        {
            get
            {
                return this.idEsquemaField;
            }
            set
            {
                this.idEsquemaField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ws.bancogalicia.com.ar/webservices/accionesautenticacionafip/autenticaryau" +
        "torizarconsumowebservicerequest/1_0_0")]
    public partial class AutenticarYAutorizarConsumoWebserviceRequestDatos
    {

        private string origenField;

        private string destinoField;

        private int idRequerimientoField;

        private string horaDesdeField;

        private string horaHastaField;

        private string servicioAConsumirField;

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string Origen
        {
            get
            {
                return this.origenField;
            }
            set
            {
                this.origenField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string Destino
        {
            get
            {
                return this.destinoField;
            }
            set
            {
                this.destinoField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public int IdRequerimiento
        {
            get
            {
                return this.idRequerimientoField;
            }
            set
            {
                this.idRequerimientoField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string HoraDesde
        {
            get
            {
                return this.horaDesdeField;
            }
            set
            {
                this.horaDesdeField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string HoraHasta
        {
            get
            {
                return this.horaHastaField;
            }
            set
            {
                this.horaHastaField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public string ServicioAConsumir
        {
            get
            {
                return this.servicioAConsumirField;
            }
            set
            {
                this.servicioAConsumirField = value;
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ws.bancogalicia.com.ar/webservices/accionesautenticacionafip/autenticaryau" +
        "torizarconsumowebserviceresponse/1_0_0")]
    public partial class AutenticarYAutorizarConsumoWebserviceResponse
    {

        private BGBAResultadoOperacion bGBAResultadoOperacionField;

        private AutenticarYAutorizarConsumoWebserviceResponseDatos datosField;

        private BGBAResultadoOperacionLogLogItem[] bGBAResultadoOperacionLogField;

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://ws.bancogalicia.com.ar/webservices/globales/bgbaresultadooperacion/2_0_0", Order = 0)]
        public BGBAResultadoOperacion BGBAResultadoOperacion
        {
            get
            {
                return this.bGBAResultadoOperacionField;
            }
            set
            {
                this.bGBAResultadoOperacionField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public AutenticarYAutorizarConsumoWebserviceResponseDatos Datos
        {
            get
            {
                return this.datosField;
            }
            set
            {
                this.datosField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Namespace = "http://ws.bancogalicia.com.ar/webservices/globales/bgbaresultadooperacion/2_0_0", Order = 2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("LogItem", IsNullable = false)]
        public BGBAResultadoOperacionLogLogItem[] BGBAResultadoOperacionLog
        {
            get
            {
                return this.bGBAResultadoOperacionLogField;
            }
            set
            {
                this.bGBAResultadoOperacionLogField = value;
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ws.bancogalicia.com.ar/webservices/globales/bgbaresultadooperacion/2_0_0")]
    public partial class BGBAResultadoOperacion
    {

        private severidad severidadField;

        private string codigoField;

        private string descripcionField;

        private string tipoField;

        private string uRLDetalleField;

        private BGBAResultadoOperacionIdRespuesta idRespuestaField;

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public severidad Severidad
        {
            get
            {
                return this.severidadField;
            }
            set
            {
                this.severidadField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string Codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string Descripcion
        {
            get
            {
                return this.descripcionField;
            }
            set
            {
                this.descripcionField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string Tipo
        {
            get
            {
                return this.tipoField;
            }
            set
            {
                this.tipoField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string URLDetalle
        {
            get
            {
                return this.uRLDetalleField;
            }
            set
            {
                this.uRLDetalleField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public BGBAResultadoOperacionIdRespuesta IdRespuesta
        {
            get
            {
                return this.idRespuestaField;
            }
            set
            {
                this.idRespuestaField = value;
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ws.bancogalicia.com.ar/webservices/globales/bgbaresultadooperacion/2_0_0")]
    public enum severidad
    {

        /// <comentarios/>
        OK,

        /// <comentarios/>
        INFO,

        /// <comentarios/>
        WARNING,

        /// <comentarios/>
        ERROR,
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ws.bancogalicia.com.ar/webservices/globales/bgbaresultadooperacion/2_0_0")]
    public partial class BGBAResultadoOperacionIdRespuesta
    {

        private string nombreProveedorField;

        private string valueField;

        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string nombreProveedor
        {
            get
            {
                return this.nombreProveedorField;
            }
            set
            {
                this.nombreProveedorField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ws.bancogalicia.com.ar/webservices/accionesautenticacionafip/autenticaryau" +
        "torizarconsumowebserviceresponse/1_0_0")]
    public partial class AutenticarYAutorizarConsumoWebserviceResponseDatos
    {

        private AutenticarYAutorizarConsumoWebserviceResponseDatosCredenciales credencialesField;

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public AutenticarYAutorizarConsumoWebserviceResponseDatosCredenciales Credenciales
        {
            get
            {
                return this.credencialesField;
            }
            set
            {
                this.credencialesField = value;
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ws.bancogalicia.com.ar/webservices/accionesautenticacionafip/autenticaryau" +
        "torizarconsumowebserviceresponse/1_0_0")]
    public partial class AutenticarYAutorizarConsumoWebserviceResponseDatosCredenciales
    {

        private string tokenField;

        private string firmaField;

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string Token
        {
            get
            {
                return this.tokenField;
            }
            set
            {
                this.tokenField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string Firma
        {
            get
            {
                return this.firmaField;
            }
            set
            {
                this.firmaField = value;
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ws.bancogalicia.com.ar/webservices/globales/bgbaresultadooperacion/2_0_0")]
    public partial class BGBAResultadoOperacionLogLogItem
    {

        private severidad2 severidadField;

        private string codigoField;

        private string descripcionField;

        private string tipoField;

        private string uRLDetalleField;

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public severidad2 Severidad
        {
            get
            {
                return this.severidadField;
            }
            set
            {
                this.severidadField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string Codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string Descripcion
        {
            get
            {
                return this.descripcionField;
            }
            set
            {
                this.descripcionField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string Tipo
        {
            get
            {
                return this.tipoField;
            }
            set
            {
                this.tipoField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string URLDetalle
        {
            get
            {
                return this.uRLDetalleField;
            }
            set
            {
                this.uRLDetalleField = value;
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ws.bancogalicia.com.ar/webservices/globales/bgbaresultadooperacion/2_0_0")]
    public enum severidad2
    {

        /// <comentarios/>
        INFO,

        /// <comentarios/>
        WARNING,

        /// <comentarios/>
        ERROR,
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "AutenticarYAutorizarConsumoWebservice", WrapperNamespace = "http://ws.bancogalicia.com.ar/webservices/accionesautenticacionafip/autenticaryau" +
        "torizarconsumowebservicerequest/1_0_0", IsWrapped = true)]
    public partial class AutenticarYAutorizarConsumoWebserviceRequest1
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://ws.bancogalicia.com.ar/webservices/accionesautenticacionafip/autenticaryau" +
            "torizarconsumowebservicerequest/1_0_0", Order = 0)]
        public AutenticarYAutorizarConsumoWebserviceRequest AutenticarYAutorizarConsumoWebserviceRequest;

        public AutenticarYAutorizarConsumoWebserviceRequest1()
        {
        }

        public AutenticarYAutorizarConsumoWebserviceRequest1(AutenticarYAutorizarConsumoWebserviceRequest AutenticarYAutorizarConsumoWebserviceRequest)
        {
            this.AutenticarYAutorizarConsumoWebserviceRequest = AutenticarYAutorizarConsumoWebserviceRequest;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "AutenticarYAutorizarConsumoWebserviceResult", WrapperNamespace = "http://ws.bancogalicia.com.ar/webservices/accionesautenticacionafip/autenticaryau" +
        "torizarconsumowebserviceresponse/1_0_0", IsWrapped = true)]
    public partial class AutenticarYAutorizarConsumoWebserviceResponse1
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://ws.bancogalicia.com.ar/webservices/accionesautenticacionafip/autenticaryau" +
            "torizarconsumowebserviceresponse/1_0_0", Order = 0)]
        public AutenticarYAutorizarConsumoWebserviceResponse AutenticarYAutorizarConsumoWebserviceResponse;

        public AutenticarYAutorizarConsumoWebserviceResponse1()
        {
        }

        public AutenticarYAutorizarConsumoWebserviceResponse1(AutenticarYAutorizarConsumoWebserviceResponse AutenticarYAutorizarConsumoWebserviceResponse)
        {
            this.AutenticarYAutorizarConsumoWebserviceResponse = AutenticarYAutorizarConsumoWebserviceResponse;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AccionesAutenticacionAFIPChannel : AccionesAutenticacionAFIP, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccionesAutenticacionAFIPClient : System.ServiceModel.ClientBase<AccionesAutenticacionAFIP>, AccionesAutenticacionAFIP
    {

        public AccionesAutenticacionAFIPClient()
        {
        }

        public AccionesAutenticacionAFIPClient(string endpointConfigurationName) :
                base(endpointConfigurationName)
        {
        }

        public AccionesAutenticacionAFIPClient(string endpointConfigurationName, string remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public AccionesAutenticacionAFIPClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public AccionesAutenticacionAFIPClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AutenticarYAutorizarConsumoWebserviceResponse1 AccionesAutenticacionAFIP.AutenticarYAutorizarConsumoWebservice(AutenticarYAutorizarConsumoWebserviceRequest1 request)
        {
            return base.Channel.AutenticarYAutorizarConsumoWebservice(request);
        }

        public AutenticarYAutorizarConsumoWebserviceResponse AutenticarYAutorizarConsumoWebservice(AutenticarYAutorizarConsumoWebserviceRequest AutenticarYAutorizarConsumoWebserviceRequest)
        {
            AutenticarYAutorizarConsumoWebserviceRequest1 inValue = new AutenticarYAutorizarConsumoWebserviceRequest1();
            inValue.AutenticarYAutorizarConsumoWebserviceRequest = AutenticarYAutorizarConsumoWebserviceRequest;
            AutenticarYAutorizarConsumoWebserviceResponse1 retVal = ((AccionesAutenticacionAFIP)(this)).AutenticarYAutorizarConsumoWebservice(inValue);
            return retVal.AutenticarYAutorizarConsumoWebserviceResponse;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AutenticarYAutorizarConsumoWebserviceResponse1> AccionesAutenticacionAFIP.AutenticarYAutorizarConsumoWebserviceAsync(AutenticarYAutorizarConsumoWebserviceRequest1 request)
        {
            return base.Channel.AutenticarYAutorizarConsumoWebserviceAsync(request);
        }

        public System.Threading.Tasks.Task<AutenticarYAutorizarConsumoWebserviceResponse1> AutenticarYAutorizarConsumoWebserviceAsync(AutenticarYAutorizarConsumoWebserviceRequest AutenticarYAutorizarConsumoWebserviceRequest)
        {
            AutenticarYAutorizarConsumoWebserviceRequest1 inValue = new AutenticarYAutorizarConsumoWebserviceRequest1();
            inValue.AutenticarYAutorizarConsumoWebserviceRequest = AutenticarYAutorizarConsumoWebserviceRequest;
            return ((AccionesAutenticacionAFIP)(this)).AutenticarYAutorizarConsumoWebserviceAsync(inValue);
        }
    }
    namespace ws.bancogalicia.com.ar.webservices.globales.bgbaresultadooperacion._2_0_0
    {


        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Xml.Serialization.XmlSchemaProviderAttribute("ExportSchema")]
        [System.Xml.Serialization.XmlRootAttribute(IsNullable = false)]
        public partial class BGBAResultadoOperacionFalla : object, System.Xml.Serialization.IXmlSerializable
        {

            private System.Xml.XmlNode[] nodesField;

            private static System.Xml.XmlQualifiedName typeName = new System.Xml.XmlQualifiedName("BGBAResultadoOperacionFalla", "http://ws.bancogalicia.com.ar/webservices/globales/bgbaresultadooperacion/2_0_0");

            public System.Xml.XmlNode[] Nodes
            {
                get
                {
                    return this.nodesField;
                }
                set
                {
                    this.nodesField = value;
                }
            }

            public void ReadXml(System.Xml.XmlReader reader)
            {
                this.nodesField = System.Runtime.Serialization.XmlSerializableServices.ReadNodes(reader);
            }

            public void WriteXml(System.Xml.XmlWriter writer)
            {
                System.Runtime.Serialization.XmlSerializableServices.WriteNodes(writer, this.Nodes);
            }

            public System.Xml.Schema.XmlSchema GetSchema()
            {
                return null;
            }

            public static System.Xml.XmlQualifiedName ExportSchema(System.Xml.Schema.XmlSchemaSet schemas)
            {
                System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(schemas, typeName);
                return typeName;
            }
        }
    }
}