//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using Core.N.Models;
using Newtonsoft.Json;

namespace Models.N.Afip
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://a4.soap.ws.server.puc.sr/", ConfigurationName = "PersonaServiceA4")]
    public interface PersonaServiceA4
    {

        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "return")]
        dummyResponse dummy(dummy request);

        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        System.Threading.Tasks.Task<dummyResponse> dummyAsync(dummy request);

        // CODEGEN: El parámetro 'personaReturn' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "personaReturn")]
        getPersonaResponse getPersona(getPersona request);

        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        System.Threading.Tasks.Task<getPersonaResponse> getPersonaAsync(getPersona request);
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://a4.soap.ws.server.puc.sr/")]
    public partial class dummyReturn
    {

        private string appserverField;

        private string authserverField;

        private string dbserverField;

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string appserver
        {
            get
            {
                return this.appserverField;
            }
            set
            {
                this.appserverField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string authserver
        {
            get
            {
                return this.authserverField;
            }
            set
            {
                this.authserverField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string dbserver
        {
            get
            {
                return this.dbserverField;
            }
            set
            {
                this.dbserverField = value;
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://a4.soap.ws.server.puc.sr/")]
    public partial class telefono
    {

        private long numeroField;

        private bool numeroFieldSpecified;

        private string tipoLineaField;

        private string tipoTelefonoField;

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public long numero
        {
            get
            {
                return this.numeroField;
            }
            set
            {
                this.numeroField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numeroSpecified
        {
            get
            {
                return this.numeroFieldSpecified;
            }
            set
            {
                this.numeroFieldSpecified = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string tipoLinea
        {
            get
            {
                return this.tipoLineaField;
            }
            set
            {
                this.tipoLineaField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string tipoTelefono
        {
            get
            {
                return this.tipoTelefonoField;
            }
            set
            {
                this.tipoTelefonoField = value;
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://a4.soap.ws.server.puc.sr/")]
    public partial class relacion
    {

        private System.DateTime ffRelacionField;

        private bool ffRelacionFieldSpecified;

        private System.DateTime ffVencimientoField;

        private bool ffVencimientoFieldSpecified;

        private long idPersonaField;

        private bool idPersonaFieldSpecified;

        private long idPersonaAsociadaField;

        private bool idPersonaAsociadaFieldSpecified;

        private string subtipoRelacionField;

        private string tipoRelacionField;

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public System.DateTime ffRelacion
        {
            get
            {
                return this.ffRelacionField;
            }
            set
            {
                this.ffRelacionField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ffRelacionSpecified
        {
            get
            {
                return this.ffRelacionFieldSpecified;
            }
            set
            {
                this.ffRelacionFieldSpecified = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public System.DateTime ffVencimiento
        {
            get
            {
                return this.ffVencimientoField;
            }
            set
            {
                this.ffVencimientoField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ffVencimientoSpecified
        {
            get
            {
                return this.ffVencimientoFieldSpecified;
            }
            set
            {
                this.ffVencimientoFieldSpecified = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public long idPersona
        {
            get
            {
                return this.idPersonaField;
            }
            set
            {
                this.idPersonaField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idPersonaSpecified
        {
            get
            {
                return this.idPersonaFieldSpecified;
            }
            set
            {
                this.idPersonaFieldSpecified = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public long idPersonaAsociada
        {
            get
            {
                return this.idPersonaAsociadaField;
            }
            set
            {
                this.idPersonaAsociadaField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idPersonaAsociadaSpecified
        {
            get
            {
                return this.idPersonaAsociadaFieldSpecified;
            }
            set
            {
                this.idPersonaAsociadaFieldSpecified = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public string subtipoRelacion
        {
            get
            {
                return this.subtipoRelacionField;
            }
            set
            {
                this.subtipoRelacionField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
        public string tipoRelacion
        {
            get
            {
                return this.tipoRelacionField;
            }
            set
            {
                this.tipoRelacionField = value;
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://a4.soap.ws.server.puc.sr/")]
    public partial class regimen
    {

        private string descripcionRegimenField;

        private int diaPeriodoField;

        private bool diaPeriodoFieldSpecified;

        private string estadoField;

        private int idImpuestoField;

        private bool idImpuestoFieldSpecified;

        private int idRegimenField;

        private bool idRegimenFieldSpecified;

        private int periodoField;

        private bool periodoFieldSpecified;

        private string tipoRegimenField;

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string descripcionRegimen
        {
            get
            {
                return this.descripcionRegimenField;
            }
            set
            {
                this.descripcionRegimenField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public int diaPeriodo
        {
            get
            {
                return this.diaPeriodoField;
            }
            set
            {
                this.diaPeriodoField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool diaPeriodoSpecified
        {
            get
            {
                return this.diaPeriodoFieldSpecified;
            }
            set
            {
                this.diaPeriodoFieldSpecified = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string estado
        {
            get
            {
                return this.estadoField;
            }
            set
            {
                this.estadoField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public int idImpuesto
        {
            get
            {
                return this.idImpuestoField;
            }
            set
            {
                this.idImpuestoField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idImpuestoSpecified
        {
            get
            {
                return this.idImpuestoFieldSpecified;
            }
            set
            {
                this.idImpuestoFieldSpecified = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public int idRegimen
        {
            get
            {
                return this.idRegimenField;
            }
            set
            {
                this.idRegimenField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idRegimenSpecified
        {
            get
            {
                return this.idRegimenFieldSpecified;
            }
            set
            {
                this.idRegimenFieldSpecified = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
        public int periodo
        {
            get
            {
                return this.periodoField;
            }
            set
            {
                this.periodoField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool periodoSpecified
        {
            get
            {
                return this.periodoFieldSpecified;
            }
            set
            {
                this.periodoFieldSpecified = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 6)]
        public string tipoRegimen
        {
            get
            {
                return this.tipoRegimenField;
            }
            set
            {
                this.tipoRegimenField = value;
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://a4.soap.ws.server.puc.sr/")]
    public partial class impuesto
    {

        private string descripcionImpuestoField;

        private int diaPeriodoField;

        private bool diaPeriodoFieldSpecified;

        private string estadoField;

        private System.DateTime ffInscripcionField;

        private bool ffInscripcionFieldSpecified;

        private int idImpuestoField;

        private bool idImpuestoFieldSpecified;

        private int periodoField;

        private bool periodoFieldSpecified;

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string descripcionImpuesto
        {
            get
            {
                return this.descripcionImpuestoField;
            }
            set
            {
                this.descripcionImpuestoField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public int diaPeriodo
        {
            get
            {
                return this.diaPeriodoField;
            }
            set
            {
                this.diaPeriodoField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool diaPeriodoSpecified
        {
            get
            {
                return this.diaPeriodoFieldSpecified;
            }
            set
            {
                this.diaPeriodoFieldSpecified = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string estado
        {
            get
            {
                return this.estadoField;
            }
            set
            {
                this.estadoField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public System.DateTime ffInscripcion
        {
            get
            {
                return this.ffInscripcionField;
            }
            set
            {
                this.ffInscripcionField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ffInscripcionSpecified
        {
            get
            {
                return this.ffInscripcionFieldSpecified;
            }
            set
            {
                this.ffInscripcionFieldSpecified = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public int idImpuesto
        {
            get
            {
                return this.idImpuestoField;
            }
            set
            {
                this.idImpuestoField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idImpuestoSpecified
        {
            get
            {
                return this.idImpuestoFieldSpecified;
            }
            set
            {
                this.idImpuestoFieldSpecified = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
        public int periodo
        {
            get
            {
                return this.periodoField;
            }
            set
            {
                this.periodoField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool periodoSpecified
        {
            get
            {
                return this.periodoFieldSpecified;
            }
            set
            {
                this.periodoFieldSpecified = value;
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://a4.soap.ws.server.puc.sr/")]
    public partial class email
    {

        private string direccionField;

        private string estadoField;

        private string tipoEmailField;

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string direccion
        {
            get
            {
                return this.direccionField;
            }
            set
            {
                this.direccionField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string estado
        {
            get
            {
                return this.estadoField;
            }
            set
            {
                this.estadoField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string tipoEmail
        {
            get
            {
                return this.tipoEmailField;
            }
            set
            {
                this.tipoEmailField = value;
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://a4.soap.ws.server.puc.sr/")]
    public partial class domicilio
    {

        private string codPostalField;

        private string datoAdicionalField;

        private string descripcionProvinciaField;

        private string direccionField;

        private int idProvinciaField;

        private bool idProvinciaFieldSpecified;

        private string localidadField;

        private string tipoDatoAdicionalField;

        private string tipoDomicilioField;

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string codPostal
        {
            get
            {
                return this.codPostalField;
            }
            set
            {
                this.codPostalField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string datoAdicional
        {
            get
            {
                return this.datoAdicionalField;
            }
            set
            {
                this.datoAdicionalField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string descripcionProvincia
        {
            get
            {
                return this.descripcionProvinciaField;
            }
            set
            {
                this.descripcionProvinciaField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public string direccion
        {
            get
            {
                return this.direccionField;
            }
            set
            {
                this.direccionField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public int idProvincia
        {
            get
            {
                return this.idProvinciaField;
            }
            set
            {
                this.idProvinciaField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idProvinciaSpecified
        {
            get
            {
                return this.idProvinciaFieldSpecified;
            }
            set
            {
                this.idProvinciaFieldSpecified = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
        public string localidad
        {
            get
            {
                return this.localidadField;
            }
            set
            {
                this.localidadField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 6)]
        public string tipoDatoAdicional
        {
            get
            {
                return this.tipoDatoAdicionalField;
            }
            set
            {
                this.tipoDatoAdicionalField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 7)]
        public string tipoDomicilio
        {
            get
            {
                return this.tipoDomicilioField;
            }
            set
            {
                this.tipoDomicilioField = value;
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://a4.soap.ws.server.puc.sr/")]
    public partial class dependencia
    {

        private string descripcionDependenciaField;

        private int idDependenciaField;

        private bool idDependenciaFieldSpecified;

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string descripcionDependencia
        {
            get
            {
                return this.descripcionDependenciaField;
            }
            set
            {
                this.descripcionDependenciaField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public int idDependencia
        {
            get
            {
                return this.idDependenciaField;
            }
            set
            {
                this.idDependenciaField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idDependenciaSpecified
        {
            get
            {
                return this.idDependenciaFieldSpecified;
            }
            set
            {
                this.idDependenciaFieldSpecified = value;
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://a4.soap.ws.server.puc.sr/")]
    public partial class categoria
    {

        private string descripcionCategoriaField;

        private string estadoField;

        private int idCategoriaField;

        private bool idCategoriaFieldSpecified;

        private int idImpuestoField;

        private bool idImpuestoFieldSpecified;

        private int periodoField;

        private bool periodoFieldSpecified;

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string descripcionCategoria
        {
            get
            {
                return this.descripcionCategoriaField;
            }
            set
            {
                this.descripcionCategoriaField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string estado
        {
            get
            {
                return this.estadoField;
            }
            set
            {
                this.estadoField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public int idCategoria
        {
            get
            {
                return this.idCategoriaField;
            }
            set
            {
                this.idCategoriaField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idCategoriaSpecified
        {
            get
            {
                return this.idCategoriaFieldSpecified;
            }
            set
            {
                this.idCategoriaFieldSpecified = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public int idImpuesto
        {
            get
            {
                return this.idImpuestoField;
            }
            set
            {
                this.idImpuestoField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idImpuestoSpecified
        {
            get
            {
                return this.idImpuestoFieldSpecified;
            }
            set
            {
                this.idImpuestoFieldSpecified = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public int periodo
        {
            get
            {
                return this.periodoField;
            }
            set
            {
                this.periodoField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool periodoSpecified
        {
            get
            {
                return this.periodoFieldSpecified;
            }
            set
            {
                this.periodoFieldSpecified = value;
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://a4.soap.ws.server.puc.sr/")]
    public partial class actividad
    {

        private string descripcionActividadField;

        private long idActividadField;

        private bool idActividadFieldSpecified;

        private int nomencladorField;

        private bool nomencladorFieldSpecified;

        private int ordenField;

        private bool ordenFieldSpecified;

        private int periodoField;

        private bool periodoFieldSpecified;

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string descripcionActividad
        {
            get
            {
                return this.descripcionActividadField;
            }
            set
            {
                this.descripcionActividadField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public long idActividad
        {
            get
            {
                return this.idActividadField;
            }
            set
            {
                this.idActividadField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idActividadSpecified
        {
            get
            {
                return this.idActividadFieldSpecified;
            }
            set
            {
                this.idActividadFieldSpecified = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public int nomenclador
        {
            get
            {
                return this.nomencladorField;
            }
            set
            {
                this.nomencladorField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nomencladorSpecified
        {
            get
            {
                return this.nomencladorFieldSpecified;
            }
            set
            {
                this.nomencladorFieldSpecified = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public int orden
        {
            get
            {
                return this.ordenField;
            }
            set
            {
                this.ordenField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ordenSpecified
        {
            get
            {
                return this.ordenFieldSpecified;
            }
            set
            {
                this.ordenFieldSpecified = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public int periodo
        {
            get
            {
                return this.periodoField;
            }
            set
            {
                this.periodoField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool periodoSpecified
        {
            get
            {
                return this.periodoFieldSpecified;
            }
            set
            {
                this.periodoFieldSpecified = value;
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://a4.soap.ws.server.puc.sr/")]
    public partial class persona
    {

        private actividad[] actividadField;

        private string apellidoField;

        private int cantidadSociosEmpresaMonoField;

        private bool cantidadSociosEmpresaMonoFieldSpecified;

        private categoria[] categoriaField;

        private System.Nullable<long>[] claveInactivaAsociadaField;

        private dependencia dependenciaField;

        private domicilio[] domicilioField;

        private email[] emailField;

        private string estadoClaveField;

        private System.DateTime fechaContratoSocialField;

        private bool fechaContratoSocialFieldSpecified;

        private System.DateTime fechaFallecimientoField;

        private bool fechaFallecimientoFieldSpecified;

        private System.DateTime fechaInscripcionField;

        private bool fechaInscripcionFieldSpecified;

        private System.DateTime fechaJubiladoField;

        private bool fechaJubiladoFieldSpecified;

        private System.DateTime fechaNacimientoField;

        private bool fechaNacimientoFieldSpecified;

        private System.DateTime fechaVencimientoMigracionField;

        private bool fechaVencimientoMigracionFieldSpecified;

        private string formaJuridicaField;

        private long idPersonaField;

        private bool idPersonaFieldSpecified;

        private impuesto[] impuestoField;

        private int leyJubilacionField;

        private bool leyJubilacionFieldSpecified;

        private string localidadInscripcionField;

        private int mesCierreField;

        private bool mesCierreFieldSpecified;

        private string nombreField;

        private string numeroDocumentoField;

        private long numeroInscripcionField;

        private bool numeroInscripcionFieldSpecified;

        private string organismoInscripcionField;

        private string organismoOriginanteField;

        private double porcentajeCapitalNacionalField;

        private bool porcentajeCapitalNacionalFieldSpecified;

        private string provinciaInscripcionField;

        private string razonSocialField;

        private regimen[] regimenField;

        private relacion[] relacionField;

        private string sexoField;

        private telefono[] telefonoField;

        private string tipoClaveField;

        private string tipoDocumentoField;

        private string tipoOrganismoOriginanteField;

        private string tipoPersonaField;

        private string tipoResidenciaField;

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("actividad", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true, Order = 0)]
        [JsonConverter(typeof(SingleValueArrayConverter<actividad>))]
        public actividad[] actividad
        {
            get
            {
                return this.actividadField;
            }
            set
            {
                this.actividadField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string apellido
        {
            get
            {
                return this.apellidoField;
            }
            set
            {
                this.apellidoField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public int cantidadSociosEmpresaMono
        {
            get
            {
                return this.cantidadSociosEmpresaMonoField;
            }
            set
            {
                this.cantidadSociosEmpresaMonoField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cantidadSociosEmpresaMonoSpecified
        {
            get
            {
                return this.cantidadSociosEmpresaMonoFieldSpecified;
            }
            set
            {
                this.cantidadSociosEmpresaMonoFieldSpecified = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("categoria", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true, Order = 3)]
        [JsonConverter(typeof(SingleValueArrayConverter<categoria>))]
        public categoria[] categoria
        {
            get
            {
                return this.categoriaField;
            }
            set
            {
                this.categoriaField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("claveInactivaAsociada", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true, Order = 4)]
        public System.Nullable<long>[] claveInactivaAsociada
        {
            get
            {
                return this.claveInactivaAsociadaField;
            }
            set
            {
                this.claveInactivaAsociadaField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
        [JsonConverter(typeof(SingleValueArrayConverter<dependencia>))]
        public dependencia dependencia
        {
            get
            {
                return this.dependenciaField;
            }
            set
            {
                this.dependenciaField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("domicilio", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true, Order = 6)]
        [JsonConverter(typeof(SingleValueArrayConverter<domicilio>))]
        public domicilio[] domicilio
        {
            get
            {
                return this.domicilioField;
            }
            set
            {
                this.domicilioField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("email", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true, Order = 7)]
        [JsonConverter(typeof(SingleValueArrayConverter<email>))]
        public email[] email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 8)]
        public string estadoClave
        {
            get
            {
                return this.estadoClaveField;
            }
            set
            {
                this.estadoClaveField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 9)]
        public System.DateTime fechaContratoSocial
        {
            get
            {
                return this.fechaContratoSocialField;
            }
            set
            {
                this.fechaContratoSocialField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaContratoSocialSpecified
        {
            get
            {
                return this.fechaContratoSocialFieldSpecified;
            }
            set
            {
                this.fechaContratoSocialFieldSpecified = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 10)]
        public System.DateTime fechaFallecimiento
        {
            get
            {
                return this.fechaFallecimientoField;
            }
            set
            {
                this.fechaFallecimientoField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaFallecimientoSpecified
        {
            get
            {
                return this.fechaFallecimientoFieldSpecified;
            }
            set
            {
                this.fechaFallecimientoFieldSpecified = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 11)]
        public System.DateTime fechaInscripcion
        {
            get
            {
                return this.fechaInscripcionField;
            }
            set
            {
                this.fechaInscripcionField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaInscripcionSpecified
        {
            get
            {
                return this.fechaInscripcionFieldSpecified;
            }
            set
            {
                this.fechaInscripcionFieldSpecified = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 12)]
        public System.DateTime fechaJubilado
        {
            get
            {
                return this.fechaJubiladoField;
            }
            set
            {
                this.fechaJubiladoField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaJubiladoSpecified
        {
            get
            {
                return this.fechaJubiladoFieldSpecified;
            }
            set
            {
                this.fechaJubiladoFieldSpecified = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 13)]
        public System.DateTime fechaNacimiento
        {
            get
            {
                return this.fechaNacimientoField;
            }
            set
            {
                this.fechaNacimientoField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaNacimientoSpecified
        {
            get
            {
                return this.fechaNacimientoFieldSpecified;
            }
            set
            {
                this.fechaNacimientoFieldSpecified = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 14)]
        public System.DateTime fechaVencimientoMigracion
        {
            get
            {
                return this.fechaVencimientoMigracionField;
            }
            set
            {
                this.fechaVencimientoMigracionField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaVencimientoMigracionSpecified
        {
            get
            {
                return this.fechaVencimientoMigracionFieldSpecified;
            }
            set
            {
                this.fechaVencimientoMigracionFieldSpecified = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 15)]
        public string formaJuridica
        {
            get
            {
                return this.formaJuridicaField;
            }
            set
            {
                this.formaJuridicaField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 16)]
        public long idPersona
        {
            get
            {
                return this.idPersonaField;
            }
            set
            {
                this.idPersonaField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idPersonaSpecified
        {
            get
            {
                return this.idPersonaFieldSpecified;
            }
            set
            {
                this.idPersonaFieldSpecified = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("impuesto", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true, Order = 17)]
        [JsonConverter(typeof(SingleValueArrayConverter<impuesto>))]
        public impuesto[] impuesto
        {
            get
            {
                return this.impuestoField;
            }
            set
            {
                this.impuestoField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 18)]
        public int leyJubilacion
        {
            get
            {
                return this.leyJubilacionField;
            }
            set
            {
                this.leyJubilacionField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool leyJubilacionSpecified
        {
            get
            {
                return this.leyJubilacionFieldSpecified;
            }
            set
            {
                this.leyJubilacionFieldSpecified = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 19)]
        public string localidadInscripcion
        {
            get
            {
                return this.localidadInscripcionField;
            }
            set
            {
                this.localidadInscripcionField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 20)]
        public int mesCierre
        {
            get
            {
                return this.mesCierreField;
            }
            set
            {
                this.mesCierreField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mesCierreSpecified
        {
            get
            {
                return this.mesCierreFieldSpecified;
            }
            set
            {
                this.mesCierreFieldSpecified = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 21)]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 22)]
        public string numeroDocumento
        {
            get
            {
                return this.numeroDocumentoField;
            }
            set
            {
                this.numeroDocumentoField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 23)]
        public long numeroInscripcion
        {
            get
            {
                return this.numeroInscripcionField;
            }
            set
            {
                this.numeroInscripcionField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numeroInscripcionSpecified
        {
            get
            {
                return this.numeroInscripcionFieldSpecified;
            }
            set
            {
                this.numeroInscripcionFieldSpecified = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 24)]
        public string organismoInscripcion
        {
            get
            {
                return this.organismoInscripcionField;
            }
            set
            {
                this.organismoInscripcionField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 25)]
        public string organismoOriginante
        {
            get
            {
                return this.organismoOriginanteField;
            }
            set
            {
                this.organismoOriginanteField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 26)]
        public double porcentajeCapitalNacional
        {
            get
            {
                return this.porcentajeCapitalNacionalField;
            }
            set
            {
                this.porcentajeCapitalNacionalField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool porcentajeCapitalNacionalSpecified
        {
            get
            {
                return this.porcentajeCapitalNacionalFieldSpecified;
            }
            set
            {
                this.porcentajeCapitalNacionalFieldSpecified = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 27)]
        public string provinciaInscripcion
        {
            get
            {
                return this.provinciaInscripcionField;
            }
            set
            {
                this.provinciaInscripcionField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 28)]
        public string razonSocial
        {
            get
            {
                return this.razonSocialField;
            }
            set
            {
                this.razonSocialField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("regimen", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true, Order = 29)]
        [JsonConverter(typeof(SingleValueArrayConverter<regimen>))]
        public regimen[] regimen
        {
            get
            {
                return this.regimenField;
            }
            set
            {
                this.regimenField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("relacion", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true, Order = 30)]
        [JsonConverter(typeof(SingleValueArrayConverter<relacion>))]
        public relacion[] relacion
        {
            get
            {
                return this.relacionField;
            }
            set
            {
                this.relacionField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 31)]
        public string sexo
        {
            get
            {
                return this.sexoField;
            }
            set
            {
                this.sexoField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("telefono", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true, Order = 32)]
        [JsonConverter(typeof(SingleValueArrayConverter<telefono>))]
        public telefono[] telefono
        {
            get
            {
                return this.telefonoField;
            }
            set
            {
                this.telefonoField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 33)]
        public string tipoClave
        {
            get
            {
                return this.tipoClaveField;
            }
            set
            {
                this.tipoClaveField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 34)]
        public string tipoDocumento
        {
            get
            {
                return this.tipoDocumentoField;
            }
            set
            {
                this.tipoDocumentoField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 35)]
        public string tipoOrganismoOriginante
        {
            get
            {
                return this.tipoOrganismoOriginanteField;
            }
            set
            {
                this.tipoOrganismoOriginanteField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 36)]
        public string tipoPersona
        {
            get
            {
                return this.tipoPersonaField;
            }
            set
            {
                this.tipoPersonaField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 37)]
        public string tipoResidencia
        {
            get
            {
                return this.tipoResidenciaField;
            }
            set
            {
                this.tipoResidenciaField = value;
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://a4.soap.ws.server.puc.sr/")]
    public partial class metadata
    {

        private System.DateTime fechaHoraField;

        private bool fechaHoraFieldSpecified;

        private string servidorField;

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public System.DateTime fechaHora
        {
            get
            {
                return this.fechaHoraField;
            }
            set
            {
                this.fechaHoraField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaHoraSpecified
        {
            get
            {
                return this.fechaHoraFieldSpecified;
            }
            set
            {
                this.fechaHoraFieldSpecified = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string servidor
        {
            get
            {
                return this.servidorField;
            }
            set
            {
                this.servidorField = value;
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://a4.soap.ws.server.puc.sr/")]
    public partial class personaReturn
    {

        private metadata metadataField;

        private persona personaField;

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public metadata metadata
        {
            get
            {
                return this.metadataField;
            }
            set
            {
                this.metadataField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public persona persona
        {
            get
            {
                return this.personaField;
            }
            set
            {
                this.personaField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "dummy", WrapperNamespace = "http://a4.soap.ws.server.puc.sr/", IsWrapped = true)]
    public partial class dummy
    {

        public dummy()
        {
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "dummyResponse", WrapperNamespace = "http://a4.soap.ws.server.puc.sr/", IsWrapped = true)]
    public partial class dummyResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://a4.soap.ws.server.puc.sr/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public dummyReturn @return;

        public dummyResponse()
        {
        }

        public dummyResponse(dummyReturn @return)
        {
            this.@return = @return;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "getPersona", WrapperNamespace = "http://a4.soap.ws.server.puc.sr/", IsWrapped = true)]
    public partial class getPersona
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://a4.soap.ws.server.puc.sr/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string token;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://a4.soap.ws.server.puc.sr/", Order = 1)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sign;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://a4.soap.ws.server.puc.sr/", Order = 2)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long cuitRepresentada;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://a4.soap.ws.server.puc.sr/", Order = 3)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long idPersona;

        public getPersona()
        {
        }

        public getPersona(string token, string sign, long cuitRepresentada, long idPersona)
        {
            this.token = token;
            this.sign = sign;
            this.cuitRepresentada = cuitRepresentada;
            this.idPersona = idPersona;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "getPersonaResponse", WrapperNamespace = "http://a4.soap.ws.server.puc.sr/", IsWrapped = true)]
    public partial class getPersonaResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://a4.soap.ws.server.puc.sr/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public personaReturn personaReturn;

        public getPersonaResponse()
        {
        }

        public getPersonaResponse(personaReturn personaReturn)
        {
            this.personaReturn = personaReturn;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PersonaServiceA4Channel : PersonaServiceA4, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PersonaServiceA4Client : System.ServiceModel.ClientBase<PersonaServiceA4>, PersonaServiceA4
    {

        public PersonaServiceA4Client()
        {
        }

        public PersonaServiceA4Client(string endpointConfigurationName) :
                base(endpointConfigurationName)
        {
        }

        public PersonaServiceA4Client(string endpointConfigurationName, string remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public PersonaServiceA4Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public PersonaServiceA4Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        dummyResponse PersonaServiceA4.dummy(dummy request)
        {
            return base.Channel.dummy(request);
        }

        public dummyReturn dummy()
        {
            dummy inValue = new dummy();
            dummyResponse retVal = ((PersonaServiceA4)(this)).dummy(inValue);
            return retVal.@return;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<dummyResponse> PersonaServiceA4.dummyAsync(dummy request)
        {
            return base.Channel.dummyAsync(request);
        }

        public System.Threading.Tasks.Task<dummyResponse> dummyAsync()
        {
            dummy inValue = new dummy();
            return ((PersonaServiceA4)(this)).dummyAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        getPersonaResponse PersonaServiceA4.getPersona(getPersona request)
        {
            return base.Channel.getPersona(request);
        }

        public personaReturn getPersona(string token, string sign, long cuitRepresentada, long idPersona)
        {
            getPersona inValue = new getPersona();
            inValue.token = token;
            inValue.sign = sign;
            inValue.cuitRepresentada = cuitRepresentada;
            inValue.idPersona = idPersona;
            getPersonaResponse retVal = ((PersonaServiceA4)(this)).getPersona(inValue);
            return retVal.personaReturn;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<getPersonaResponse> PersonaServiceA4.getPersonaAsync(getPersona request)
        {
            return base.Channel.getPersonaAsync(request);
        }

        public System.Threading.Tasks.Task<getPersonaResponse> getPersonaAsync(string token, string sign, long cuitRepresentada, long idPersona)
        {
            getPersona inValue = new getPersona();
            inValue.token = token;
            inValue.sign = sign;
            inValue.cuitRepresentada = cuitRepresentada;
            inValue.idPersona = idPersona;
            return ((PersonaServiceA4)(this)).getPersonaAsync(inValue);
        }
    }
}
