//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.Xml.Linq;
using Newtonsoft.Json;

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://ws.bancogalicia.com.ar/webservices/globales/bgbaresultadooperacion/2_0_0", ClrNamespace = "ws.bancogalicia.com.ar.webservices.globales.bgbaresultadooperacion._2_0_0")]

namespace Services.N.Autenticacion.Models.AccionesSeguridadOmnichannel
{

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://ws.bancogalicia.com.ar/webservices/accionesseguridadomnichannel/1_0_0", ConfigurationName = "AccionesSeguridadOmnichannel")]
    public interface AccionesSeguridadOmnichannel
    {

        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de contenedor (http://ws.bancogalicia.com.ar/webservices/accionesseguridadomnichannel/generarsemillarequest/1_0_0) del mensaje GenerarSemillaRequest no coincide con el valor predeterminado (http://ws.bancogalicia.com.ar/webservices/accionesseguridadomnichannel/1_0_0)
        [System.ServiceModel.OperationContractAttribute(Action = "http://ws.bancogalicia.com.ar/webservices/accionesseguridadomnichannel/generarsem" +
            "illa", ReplyAction = "*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ws.bancogalicia.com.ar.webservices.globales.bgbaresultadooperacion._2_0_0.BGBAResultadoOperacionFalla), Action = "http://ws.bancogalicia.com.ar/webservices/accionesseguridadomnichannel/generarsem" +
            "illa", Name = "BGBAResultadoOperacionFalla", Namespace = "http://ws.bancogalicia.com.ar/webservices/globales/bgbaresultadooperacion/2_0_0")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        GenerarSemillaResponse1 GenerarSemilla(GenerarSemillaRequest1 request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://ws.bancogalicia.com.ar/webservices/accionesseguridadomnichannel/generarsem" +
            "illa", ReplyAction = "*")]
        System.Threading.Tasks.Task<GenerarSemillaResponse1> GenerarSemillaAsync(GenerarSemillaRequest1 request);
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ws.bancogalicia.com.ar/webservices/accionesseguridadomnichannel/generarsem" +
        "illarequest/1_0_0")]
    public partial class GenerarSemillaRequest
    {
        
        private BGBAHeader bGBAHeaderField;
        
        private GenerarSemillaRequestDatos datosField;

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://ws.bancogalicia.com.ar/webservices/globales/bgbaheader/2_0_0", Order = 0)]
        [JsonProperty("_01:BGBAHeader")]
        public BGBAHeader BGBAHeader
        {
            get
            {
                return this.bGBAHeaderField;
            }
            set
            {
                this.bGBAHeaderField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        [JsonProperty("_0:Datos")]
        public GenerarSemillaRequestDatos Datos
        {
            get
            {
                return this.datosField;
            }
            set
            {
                this.datosField = value;
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ws.bancogalicia.com.ar/webservices/globales/bgbaheader/2_0_0")]
    public partial class BGBAHeader
    {
        
        private Identificadores identificadoresField;
        
        private ModuloAplicativo moduloAplicativoField;
        
        private equipo equipoField;
        
        private Origen origenField;

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        [JsonProperty("_01:Identificadores")]
        public Identificadores Identificadores
        {
            get
            {
                return this.identificadoresField;
            }
            set
            {
                this.identificadoresField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        [JsonProperty("_01:ModuloAplicativo")]
        public ModuloAplicativo ModuloAplicativo
        {
            get
            {
                return this.moduloAplicativoField;
            }
            set
            {
                this.moduloAplicativoField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        [JsonProperty("_01:Equipo", NullValueHandling = NullValueHandling.Ignore)]
        public equipo Equipo
        {
            get
            {
                return this.equipoField;
            }
            set
            {
                this.equipoField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        [JsonProperty("_01:Origen")]
        public Origen Origen
        {
            get
            {
                return this.origenField;
            }
            set
            {
                this.origenField = value;
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ws.bancogalicia.com.ar/webservices/globales/bgbaheader/2_0_0")]
    public partial class Identificadores
    {
        
        private idMensaje idMensajeField;
        
        private idMensaje idMensajeAnteriorField;
        
        private idMensaje idOperacionField;

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        [JsonProperty("_01:IdMensaje")]
        public idMensaje IdMensaje
        {
            get
            {
                return this.idMensajeField;
            }
            set
            {
                this.idMensajeField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        [JsonProperty("_01:IdMensajeAnterior")]
        public idMensaje IdMensajeAnterior
        {
            get
            {
                return this.idMensajeAnteriorField;
            }
            set
            {
                this.idMensajeAnteriorField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        [JsonProperty("_01:IdOperacion")]
        public idMensaje IdOperacion
        {
            get
            {
                return this.idOperacionField;
            }
            set
            {
                this.idOperacionField = value;
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ws.bancogalicia.com.ar/webservices/globales/bgbaheader/2_0_0")]
    public partial class idMensaje
    {
        
        private string idEsquemaField;
        
        private string valueField;

        public idMensaje()
        {
            this.idEsquemaField = "UUI";
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("UUI")]
        [JsonProperty("@idEsquema")]
        public string idEsquema
        {
            get
            {
                return this.idEsquemaField;
            }
            set
            {
                this.idEsquemaField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlTextAttribute()]
        [JsonProperty("$")]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ws.bancogalicia.com.ar/webservices/globales/bgbatiposbase/3_0_0")]
    public partial class codigo
    {

        private string idListaField;

        private string organizacionIdListaField;

        private string valueField;

        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "token")]
        public string idLista
        {
            get
            {
                return this.idListaField;
            }
            set
            {
                this.idListaField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "token")]
        public string organizacionIdLista
        {
            get
            {
                return this.organizacionIdListaField;
            }
            set
            {
                this.organizacionIdListaField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlTextAttribute(DataType = "token")]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ws.bancogalicia.com.ar/webservices/globales/bgbatiposbase/3_0_0")]
    public partial class id
    {
        
        private string idEsquemaField;
        private string organizacionIdEsquemaField;
        private string valueField;

        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "token")]
        [JsonProperty("@idEsquema",NullValueHandling = NullValueHandling.Ignore)]
        public string idEsquema
        {
            get
            {
                return this.idEsquemaField;
            }
            set
            {
                this.idEsquemaField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "token")]
        [JsonProperty("@organizacionIdEsquema",NullValueHandling = NullValueHandling.Ignore)]
        public string organizacionIdEsquema
        {
            get
            {
                return this.organizacionIdEsquemaField;
            }
            set
            {
                this.organizacionIdEsquemaField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlTextAttribute()]
        [JsonProperty("$")]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ws.bancogalicia.com.ar/webservices/globales/bgbaheader/2_0_0")]
    public partial class organizacionInterna
    {
        private string tipoField;
        
        private ulong idField;

        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]

        [JsonProperty("@tipo")]
        public string tipo
        {
            get
            {
                return this.tipoField;
            }
            set
            {
                this.tipoField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [JsonProperty("@id")]
        public ulong id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ws.bancogalicia.com.ar/webservices/globales/bgbaheader/2_0_0")]
    public partial class Origen
    {
        
        private ModuloAplicativo moduloAplicativoField;
        
        private string canalField;
        
        private organizacionInterna organizacionInternaField;

        private equipo equipoField;
        
        private string terminalField;

        private System.DateTime fechaHoraCreacionField;

        private bool fechaHoraCreacionFieldSpecified;
        
        private IdCliente idClienteField;
        
        private Operador operadorField;
        
        private string supervisionField;

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        [JsonProperty("_01:ModuloAplicativo")]
        public ModuloAplicativo ModuloAplicativo
        {
            get
            {
                return this.moduloAplicativoField;
            }
            set
            {
                this.moduloAplicativoField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        [JsonProperty("_01:Canal")]
        public string Canal
        {
            get
            {
                return this.canalField;
            }
            set
            {
                this.canalField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        [JsonProperty("_01:OrganizacionInterna")]
        public organizacionInterna OrganizacionInterna
        {
            get
            {
                return this.organizacionInternaField;
            }
            set
            {
                this.organizacionInternaField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        [JsonProperty("_01:Equipo", NullValueHandling = NullValueHandling.Ignore)]
        public equipo Equipo
        {
            get
            {
                return this.equipoField;
            }
            set
            {
                this.equipoField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        [JsonProperty("_01:Terminal")]
        public string Terminal
        {
            get
            {
                return this.terminalField;
            }
            set
            {
                this.terminalField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        [JsonIgnore]
        public System.DateTime FechaHoraCreacion
        {
            get
            {
                return this.fechaHoraCreacionField;
            }
            set
            {
                this.fechaHoraCreacionField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [JsonIgnore]
        public bool FechaHoraCreacionSpecified
        {
            get
            {
                return this.fechaHoraCreacionFieldSpecified;
            }
            set
            {
                this.fechaHoraCreacionFieldSpecified = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        [JsonProperty("_01:IdCliente")]
        public IdCliente IdCliente
        {
            get
            {
                return this.idClienteField;
            }
            set
            {
                this.idClienteField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        [JsonProperty("_01:Operador")]
        public Operador Operador
        {
            get
            {
                return this.operadorField;
            }
            set
            {
                this.operadorField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 8)]
        [JsonProperty("_01:Supervision")]
        public string Supervision
        {
            get
            {
                return this.supervisionField;
            }
            set
            {
                this.supervisionField = value;
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ws.bancogalicia.com.ar/webservices/globales/bgbaheader/2_0_0")]
    public partial class ModuloAplicativo
    {
        
        private string idGaliciaField;
        
        private string idConsumidorField;
        
        private string idProveedorField;

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        [JsonProperty("_01:IdGalicia")]
        public string IdGalicia
        {
            get
            {
                return this.idGaliciaField;
            }
            set
            {
                this.idGaliciaField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        [JsonProperty("_01:IdConsumidor")]
        public string IdConsumidor
        {
            get
            {
                return this.idConsumidorField;
            }
            set
            {
                this.idConsumidorField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        [JsonProperty("_01:IdProveedor")]
        public string IdProveedor
        {
            get
            {
                return this.idProveedorField;
            }
            set
            {
                this.idProveedorField = value;
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ws.bancogalicia.com.ar/webservices/globales/bgbaheader/2_0_0")]
    public partial class equipo
    {
        
        private string ipField;
        
        private string nombreField;

        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [JsonProperty("@ip")]
        public string ip
        {
            get
            {
                return this.ipField;
            }
            set
            {
                this.ipField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [JsonProperty("@nombre")]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ws.bancogalicia.com.ar/webservices/globales/bgbaheader/2_0_0")]
    public partial class IdCliente
    {

        private string idEsquemaField;

        private string valueField;

        public IdCliente()
        {
            this.idEsquemaField = "NV";
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("NV")]
        [JsonProperty("@idEsquema")]
        public string idEsquema
        {
            get
            {
                return this.idEsquemaField;
            }
            set
            {
                this.idEsquemaField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlTextAttribute()]
        [JsonProperty("$")]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ws.bancogalicia.com.ar/webservices/globales/bgbaheader/2_0_0")]
    public partial class Operador
    {

        private string idEsquemaField;

        private string valueField;

        public Operador()
        {
            this.idEsquemaField = "LEGAJO";
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("LEGAJO")]
        [JsonProperty("@idEsquema")]
        public string idEsquema
        {
            get
            {
                return this.idEsquemaField;
            }
            set
            {
                this.idEsquemaField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlTextAttribute()]
        [JsonProperty("$")]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ws.bancogalicia.com.ar/webservices/accionesseguridadomnichannel/generarsem" +
        "illarequest/1_0_0")]
    public partial class GenerarSemillaRequestDatos
    {
        private id idClienteField;

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        [JsonProperty("_0:idCliente")]
        public id idCliente
        {
            get
            {
                return this.idClienteField;
            }
            set
            {
                this.idClienteField = value;
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ws.bancogalicia.com.ar/webservices/accionesseguridadomnichannel/generarsem" +
        "illaresponse/1_0_0")]
    public partial class GenerarSemillaResponse
    {

        private BGBAResultadoOperacion bGBAResultadoOperacionField;

        private GenerarSemillaResponseDatos datosField;

        private BGBAResultadoOperacionLogLogItem[] bGBAResultadoOperacionLogField;

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://ws.bancogalicia.com.ar/webservices/globales/bgbaresultadooperacion/2_0_0", Order = 0)]
        public BGBAResultadoOperacion BGBAResultadoOperacion
        {
            get
            {
                return this.bGBAResultadoOperacionField;
            }
            set
            {
                this.bGBAResultadoOperacionField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public GenerarSemillaResponseDatos Datos
        {
            get
            {
                return this.datosField;
            }
            set
            {
                this.datosField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Namespace = "http://ws.bancogalicia.com.ar/webservices/globales/bgbaresultadooperacion/2_0_0", Order = 2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("LogItem", IsNullable = false)]
        public BGBAResultadoOperacionLogLogItem[] BGBAResultadoOperacionLog
        {
            get
            {
                return this.bGBAResultadoOperacionLogField;
            }
            set
            {
                this.bGBAResultadoOperacionLogField = value;
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ws.bancogalicia.com.ar/webservices/globales/bgbaresultadooperacion/2_0_0")]
    public partial class BGBAResultadoOperacion
    {

        private severidad severidadField;

        private string codigoField;

        private string descripcionField;

        private string tipoField;

        private string uRLDetalleField;

        private BGBAResultadoOperacionIdRespuesta idRespuestaField;

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public severidad Severidad
        {
            get
            {
                return this.severidadField;
            }
            set
            {
                this.severidadField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string Codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string Descripcion
        {
            get
            {
                return this.descripcionField;
            }
            set
            {
                this.descripcionField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string Tipo
        {
            get
            {
                return this.tipoField;
            }
            set
            {
                this.tipoField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string URLDetalle
        {
            get
            {
                return this.uRLDetalleField;
            }
            set
            {
                this.uRLDetalleField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public BGBAResultadoOperacionIdRespuesta IdRespuesta
        {
            get
            {
                return this.idRespuestaField;
            }
            set
            {
                this.idRespuestaField = value;
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ws.bancogalicia.com.ar/webservices/globales/bgbaresultadooperacion/2_0_0")]
    public enum severidad
    {

        /// <comentarios/>
        OK,

        /// <comentarios/>
        INFO,

        /// <comentarios/>
        WARNING,

        /// <comentarios/>
        ERROR,
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ws.bancogalicia.com.ar/webservices/globales/bgbaresultadooperacion/2_0_0")]
    public partial class BGBAResultadoOperacionIdRespuesta
    {

        private string nombreProveedorField;

        private string valueField;

        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string nombreProveedor
        {
            get
            {
                return this.nombreProveedorField;
            }
            set
            {
                this.nombreProveedorField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ws.bancogalicia.com.ar/webservices/accionesseguridadomnichannel/generarsem" +
        "illaresponse/1_0_0")]
    public partial class GenerarSemillaResponseDatos
    {

        private string idSesionField;

        private string semillaField;

        private GenerarSemillaResponseDatosResultado resultadoField;

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string IdSesion
        {
            get
            {
                return this.idSesionField;
            }
            set
            {
                this.idSesionField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string Semilla
        {
            get
            {
                return this.semillaField;
            }
            set
            {
                this.semillaField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public GenerarSemillaResponseDatosResultado Resultado
        {
            get
            {
                return this.resultadoField;
            }
            set
            {
                this.resultadoField = value;
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ws.bancogalicia.com.ar/webservices/accionesseguridadomnichannel/generarsem" +
        "illaresponse/1_0_0")]
    public partial class GenerarSemillaResponseDatosResultado
    {

        private string codigoField;

        private string nombreField;

        private string descripcionField;

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string Codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string Nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string Descripcion
        {
            get
            {
                return this.descripcionField;
            }
            set
            {
                this.descripcionField = value;
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ws.bancogalicia.com.ar/webservices/globales/bgbaresultadooperacion/2_0_0")]
    public partial class BGBAResultadoOperacionLogLogItem
    {

        private severidad2 severidadField;

        private string codigoField;

        private string descripcionField;

        private string tipoField;

        private string uRLDetalleField;

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public severidad2 Severidad
        {
            get
            {
                return this.severidadField;
            }
            set
            {
                this.severidadField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string Codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string Descripcion
        {
            get
            {
                return this.descripcionField;
            }
            set
            {
                this.descripcionField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string Tipo
        {
            get
            {
                return this.tipoField;
            }
            set
            {
                this.tipoField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string URLDetalle
        {
            get
            {
                return this.uRLDetalleField;
            }
            set
            {
                this.uRLDetalleField = value;
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ws.bancogalicia.com.ar/webservices/globales/bgbaresultadooperacion/2_0_0")]
    public enum severidad2
    {

        /// <comentarios/>
        INFO,

        /// <comentarios/>
        WARNING,

        /// <comentarios/>
        ERROR,
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GenerarSemilla", WrapperNamespace = "http://ws.bancogalicia.com.ar/webservices/accionesseguridadomnichannel/generarsem" +
        "illarequest/1_0_0", IsWrapped = true)]
    public partial class GenerarSemillaRequest1
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://ws.bancogalicia.com.ar/webservices/accionesseguridadomnichannel/generarsem" +
            "illarequest/1_0_0", Order = 0)]
        public GenerarSemillaRequest GenerarSemillaRequest;

        public GenerarSemillaRequest1()
        {
        }

        public GenerarSemillaRequest1(GenerarSemillaRequest GenerarSemillaRequest)
        {
            this.GenerarSemillaRequest = GenerarSemillaRequest;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GenerarSemillaResult", WrapperNamespace = "http://ws.bancogalicia.com.ar/webservices/accionesseguridadomnichannel/generarsem" +
        "illaresponse/1_0_0", IsWrapped = true)]
    public partial class GenerarSemillaResponse1
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://ws.bancogalicia.com.ar/webservices/accionesseguridadomnichannel/generarsem" +
            "illaresponse/1_0_0", Order = 0)]
        public GenerarSemillaResponse GenerarSemillaResponse;

        public GenerarSemillaResponse1()
        {
        }

        public GenerarSemillaResponse1(GenerarSemillaResponse GenerarSemillaResponse)
        {
            this.GenerarSemillaResponse = GenerarSemillaResponse;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AccionesSeguridadOmnichannelChannel : AccionesSeguridadOmnichannel, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccionesSeguridadOmnichannelClient : System.ServiceModel.ClientBase<AccionesSeguridadOmnichannel>, AccionesSeguridadOmnichannel
    {

        public AccionesSeguridadOmnichannelClient()
        {
        }

        public AccionesSeguridadOmnichannelClient(string endpointConfigurationName) :
                base(endpointConfigurationName)
        {
        }

        public AccionesSeguridadOmnichannelClient(string endpointConfigurationName, string remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public AccionesSeguridadOmnichannelClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public AccionesSeguridadOmnichannelClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GenerarSemillaResponse1 AccionesSeguridadOmnichannel.GenerarSemilla(GenerarSemillaRequest1 request)
        {
            return base.Channel.GenerarSemilla(request);
        }

        public GenerarSemillaResponse GenerarSemilla(GenerarSemillaRequest GenerarSemillaRequest)
        {
            GenerarSemillaRequest1 inValue = new GenerarSemillaRequest1();
            inValue.GenerarSemillaRequest = GenerarSemillaRequest;
            GenerarSemillaResponse1 retVal = ((AccionesSeguridadOmnichannel)(this)).GenerarSemilla(inValue);
            return retVal.GenerarSemillaResponse;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GenerarSemillaResponse1> AccionesSeguridadOmnichannel.GenerarSemillaAsync(GenerarSemillaRequest1 request)
        {
            return base.Channel.GenerarSemillaAsync(request);
        }

        public System.Threading.Tasks.Task<GenerarSemillaResponse1> GenerarSemillaAsync(GenerarSemillaRequest GenerarSemillaRequest)
        {
            GenerarSemillaRequest1 inValue = new GenerarSemillaRequest1();
            inValue.GenerarSemillaRequest = GenerarSemillaRequest;
            return ((AccionesSeguridadOmnichannel)(this)).GenerarSemillaAsync(inValue);
        }
    }
    namespace ws.bancogalicia.com.ar.webservices.globales.bgbaresultadooperacion._2_0_0
    {


        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Xml.Serialization.XmlSchemaProviderAttribute("ExportSchema")]
        [System.Xml.Serialization.XmlRootAttribute(IsNullable = false)]
        public partial class BGBAResultadoOperacionFalla : object, System.Xml.Serialization.IXmlSerializable
        {

            private System.Xml.XmlNode[] nodesField;

            private static System.Xml.XmlQualifiedName typeName = new System.Xml.XmlQualifiedName("BGBAResultadoOperacionFalla", "http://ws.bancogalicia.com.ar/webservices/globales/bgbaresultadooperacion/2_0_0");

            public System.Xml.XmlNode[] Nodes
            {
                get
                {
                    return this.nodesField;
                }
                set
                {
                    this.nodesField = value;
                }
            }

            public void ReadXml(System.Xml.XmlReader reader)
            {
                this.nodesField = System.Runtime.Serialization.XmlSerializableServices.ReadNodes(reader);
            }

            public void WriteXml(System.Xml.XmlWriter writer)
            {
                System.Runtime.Serialization.XmlSerializableServices.WriteNodes(writer, this.Nodes);
            }

            public System.Xml.Schema.XmlSchema GetSchema()
            {
                return null;
            }

            public static System.Xml.XmlQualifiedName ExportSchema(System.Xml.Schema.XmlSchemaSet schemas)
            {
                System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(schemas, typeName);
                return typeName;
            }
        }
    }
}